# Generated by Django 5.2.8 on 2026-02-11 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Felhasznalo',
            fields=[
                ('felhasznalo_id', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('teljes_nev', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('felhasznalonev', models.CharField(max_length=50)),
                ('jelszo', models.CharField(max_length=255)),
                ('szerepkor', models.CharField(choices=[('operator', 'Operátor'), ('vezeto', 'Vezető'), ('admin', 'Admin')], default='operator', max_length=20)),
            ],
        ),
    ]
