# Generated by Django 5.2.8 on 2026-03-18 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='felhasznalo',
            name='vonalkod',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
