# Generated by Django 5.2.8 on 2026-02-11 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cikk',
            fields=[
                ('cikkszam', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('tipus', models.CharField(choices=[('alapanyag', 'Alapanyag'), ('kesztermek', 'Késztermék')], max_length=20)),
                ('megnevezes', models.CharField(max_length=100)),
                ('minoseg', models.CharField(blank=True, max_length=50, null=True)),
                ('magassag', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('szelesseg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('hosszusag', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Muvelet',
            fields=[
                ('muvelet_id', models.AutoField(primary_key=True, serialize=False)),
                ('megnevezes', models.CharField(max_length=100)),
                ('koltseg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('normaido', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('partner_id', models.AutoField(primary_key=True, serialize=False)),
                ('partner_nev', models.CharField(max_length=100)),
                ('adoszam', models.CharField(blank=True, max_length=20, null=True)),
                ('cim', models.CharField(blank=True, max_length=150, null=True)),
                ('telefonszam', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Keszlet',
            fields=[
                ('cikkszam', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='gyartas_app.cikk')),
                ('aktualis_mennyiseg', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='GyartasFej',
            fields=[
                ('gyartas_id', models.AutoField(primary_key=True, serialize=False)),
                ('tervezett_mennyiseg', models.IntegerField()),
                ('jo_mennyiseg', models.IntegerField(default=0)),
                ('selejt_mennyiseg', models.IntegerField(default=0)),
                ('statusz', models.CharField(choices=[('tervezett', 'Tervezett'), ('engedelyezett', 'Engedélyezett'), ('lezart', 'Lezárt')], default='tervezett', max_length=20)),
                ('letrehozas_datuma', models.DateTimeField(auto_now_add=True)),
                ('lezaras_datuma', models.DateTimeField(blank=True, null=True)),
                ('kesztermek_cikkszam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gyartas_app.cikk')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gyartas_app.partner')),
            ],
        ),
        migrations.CreateModel(
            name='GyartasSor',
            fields=[
                ('gyartas_sor_id', models.AutoField(primary_key=True, serialize=False)),
                ('sorrend', models.IntegerField()),
                ('tervezett_db', models.IntegerField()),
                ('jo_db', models.IntegerField(default=0)),
                ('selejt_db', models.IntegerField(default=0)),
                ('gyartas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gyartas_app.gyartasfej')),
                ('muvelet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gyartas_app.muvelet')),
            ],
        ),
        migrations.CreateModel(
            name='KeszletMozgas',
            fields=[
                ('mozgas_id', models.AutoField(primary_key=True, serialize=False)),
                ('mennyiseg', models.IntegerField()),
                ('tipus', models.CharField(choices=[('felhasznalas', 'Felhasználás'), ('gyartas', 'Gyártás'), ('korrekcio', 'Korrekció')], max_length=20)),
                ('datum', models.DateTimeField(auto_now_add=True)),
                ('cikkszam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gyartas_app.cikk')),
                ('kapcsolodo_gyartas', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gyartas_app.gyartasfej')),
            ],
        ),
        migrations.CreateModel(
            name='Lejelentes',
            fields=[
                ('lejelentes_id', models.AutoField(primary_key=True, serialize=False)),
                ('bemeno_db', models.IntegerField()),
                ('jo_db', models.IntegerField()),
                ('selejt_db', models.IntegerField()),
                ('datum', models.DateTimeField(auto_now_add=True)),
                ('felhasznalo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.felhasznalo')),
                ('gyartas_sor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gyartas_app.gyartassor')),
            ],
        ),
        migrations.CreateModel(
            name='ReceptFej',
            fields=[
                ('recept_id', models.AutoField(primary_key=True, serialize=False)),
                ('anyaghanyad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('letrehozas_datuma', models.DateTimeField(auto_now_add=True)),
                ('kesztermek_cikkszam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gyartas_app.cikk')),
            ],
        ),
        migrations.CreateModel(
            name='ReceptSor',
            fields=[
                ('sor_id', models.AutoField(primary_key=True, serialize=False)),
                ('mennyiseg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('alapanyag_cikkszam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gyartas_app.cikk')),
                ('recept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gyartas_app.receptfej')),
            ],
        ),
    ]
