# Generated by Django 5.2.8 on 2026-02-12 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyartas_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receptsor',
            name='muvelet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gyartas_app.muvelet'),
        ),
        migrations.AddField(
            model_name='receptsor',
            name='sorrend',
            field=models.IntegerField(default=1),
        ),
    ]
