# Generated by Django 5.2.8 on 2026-03-18 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyartas_app', '0003_partner_email_alter_partner_cim_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lejelentes',
            name='gyartas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gyartas_app.gyartasfej'),
        ),
        migrations.AlterField(
            model_name='lejelentes',
            name='gyartas_sor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gyartas_app.gyartassor'),
        ),
    ]
