# Generated by Django 5.2.8 on 2026-03-23 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gyartas_app', '0004_lejelentes_gyartas_alter_lejelentes_gyartas_sor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keszletmozgas',
            name='cikkszam',
        ),
        migrations.RemoveField(
            model_name='keszletmozgas',
            name='kapcsolodo_gyartas',
        ),
        migrations.DeleteModel(
            name='Keszlet',
        ),
        migrations.DeleteModel(
            name='KeszletMozgas',
        ),
    ]
