# Generated by Django 5.2.8 on 2026-03-23 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyartas_app', '0005_remove_keszletmozgas_cikkszam_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keszlet',
            fields=[
                ('cikk', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='gyartas_app.cikk')),
                ('mennyiseg', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='KeszletMozgas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mennyiseg', models.FloatField()),
                ('tipus', models.CharField(choices=[('felhasznalas', 'Felhasználás'), ('gyartas', 'Gyártás'), ('korrekcio', 'Korrekció')], max_length=20)),
                ('datum', models.DateTimeField(auto_now_add=True)),
                ('cikk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gyartas_app.cikk')),
                ('gyartas', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gyartas_app.gyartasfej')),
            ],
        ),
    ]
