# Generated by Django 5.2.8 on 2026-03-23 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyartas_app', '0006_keszlet_keszletmozgas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keszlet',
            name='mennyiseg',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='keszletmozgas',
            name='mennyiseg',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
