# Generated by Django 5.2.8 on 2026-03-25 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyartas_app', '0007_alter_keszlet_mennyiseg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='keszlet',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='keszlet',
            name='cikk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gyartas_app.cikk'),
        ),
    ]
